---
- name: install apache2
  apt: name=apache2 update_cache=yes state=latest


- name: Install Apache and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
    - perl

- name: Start Apache Service
  service:
    name: apache2
    state: started
    enabled: yes
